import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Public_Sans } from 'next/font/google'

const sans = Public_Sans({
  subsets: ['latin'],
  weight: ['300', '400', '700'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={sans.className}>{children}</body>
    </html>
  )
}
